site_name: Flight Delays Predictions
site_url: https://github.com/bakr-UCB/261-Final-Project/tree/develop
site_description: An Machine Learning solusions to predict departure flight delays in the US using Spark on DataBricks.
site_author: MEDS
repo_name: 261 Final Project
repo_url: https://github.com/bakr-UCB/261-Final-Project/tree/develop
theme:
  name: material
  favicon: imgs/airplane.png
  icon:
    repo: fontawesome/brands/github
    logo: material/airplane-takeoff
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime

# plugins:
#   - social
#   - search

markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href=""  target="_blank" rel="noopener">MEDS Team</a>
# 