site_name: 261 Final Project
site_url: https://github.com/bakr-UCB/261-Final-Project/tree/develop
site_description: A simple web application that allows users to create and manage a list of tasks.
site_author: MEDS
repo_name: 261 Final Project
repo_url: https://github.com/bakr-UCB/261-Final-Project/tree/develop
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime

# plugins:
#   - social
#   - search

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
#   - attr_list
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href=""  target="_blank" rel="noopener">MEDS Team</a>
# 